### ISSUE TITLE
Supported USB dongle

### ISSUE THREAD

**Issue by 1am** [noble/noble#100]
Hello

I've tried noble on Edison board and I was wondering how this could be ported to a OSX computer. Since my mac doesn't support Bluetooth low energy out of the box but for using a Bluegiga's BLED dongle and python library https://github.com/jrowberg/bglib work fine I wonder how these two could be glued together? There's also a npm for the BLED device https://github.com/technicalmachine/bglib but I haven't yet seen it work on a computer but only on Tessel.io board.

**Comment by elimcjah** [comment]
I'm in a similar pickle.  I have a project that is requiring me to use this BLED112 dongle and want to use noble as well.
