### ISSUE TITLE
Unable to turn on notification

### ISSUE THREAD

**Issue by durlabh-insigmainc** [noble/noble#118]
We have a few BLE devices that have a service having 3 different characteristics. One of the characteristic has notify and read options. To enable notify on Android we enable notify on the characteristic and enable notification by writing [0x01, 0x0] on its descriptor. On Android and iOS, the notifications work fine and we continuously get data. However, in noble (on Debian), when we turn on notify by passing true, the callback is never called. Any suggestions?

**Comment by chanchal11** [comment]
Same problem, i also have on ubuntu. notify callback never called. But works perfect when connecting through Android.

**Comment by rabee05** [comment]
Same issue on raspberry pi . notify callback never called. But works perfect when connecting through Android or iPhone. Any helpful tips?
Thanks!
