### ISSUE TITLE
xpcError: connection interrupted

### ISSUE THREAD

**Issue by vincentsaluzzo** [noble/noble#21]
Hi,

I try a little script on my MacBookPro Retina : 

``` js
var noble = require('noble');

var serviceUUID = "8D1B321B-0356-4A3F-9194-35CDC5C7F456";
var characteristicsUUID = "A75AE96A-5C43F-4221-B6D2-C8AB33B8642B";

noble.on('stateChange', function(state) {
    if(state === "poweredOn") {
        noble.startScanning([serviceUUID], true);
    }
});

noble.on('scanStart', function() {
    console.log("Starting to scanning peripheral");
});

noble.on('scanStop', function() {
    console.log("Stopping peripheral scan");
});

noble.on('discover', function(peripheral) {
    console.log('Discovering peripheral ' + peripheral.uuid + 'at RSSI: ' + peripheral.rssi);
});
```

But when I try to execute the script I have an error : "xpcError: connection interrupted". Here is the exact output on my computer : 

```
> node index.js 
Starting to scanning peripheral
xpcError: connection interrupted
```

Nothing append after this. But I'm pretty sure I have a peripheral device activated in the proximity of my computer.

**Comment by tigoe** [comment]
I'm getting the same error with noble, running node 4.1.1, OSX 10.11.1. Looking into it now.

**Comment by tigoe** [comment]
The problem seems to only occur with discoverSomeServicesAndCharacteristics() and discoverServices(). On the other hand, discoverAllServicesAndCharacteristics() works fine.

**Comment by sandeepmistry** [comment]
@tigoe what arguments are you passing into ```discoverSomeServicesAndCharacteristics()```?

**Comment by tigoe** [comment]
I was using ([serviceUuid], callback). But I found that when I removed dashes from the uuid and made it all lower case, the problem was solved. Might be good to put in a UUID converter function that can resolve the most common formats (dashed vs undashed, upper vs lower case).
