### ISSUE TITLE
adapter state unauthorized

### ISSUE THREAD

**Issue by f14c0** [noble/noble#35]
I was running an old version of noble, over Linux and everything was ok, so until i updated noble, i get this error on terminal.

noble warning: adapter state unauthorized, please run as root or with sudo

i  run with sudo but it still no works, neither

advertisement-discovery.js

**Comment by rabertol** [comment]
hi do you have a simple example how to run a bluetooth discovering and sending?
like i am a bluetooht and can discovering and same time some else can find me?

**Comment by ozanAta** [comment]
hi , i'm trying to use multiple bluetooth dongles for scanning at the same time. My RP only uses one . What am i supposed to do in this situation. ?

**Comment by sandeepmistry** [comment]
@ozanAta your question is off topic to this issue. Please ask the question on Gitter: https://gitter.im/sandeepmistry/noble
