### ISSUE TITLE
writeHandle() parameters?

### ISSUE THREAD

**Issue by tomkubitza** [noble/noble#49]
Hi,
firstly, thanks a lot for you great work!

I was wondering how a concrete writeHandle() command would look like?

After having connected I wasn't successfully with the following parameters yet:

``` js
...
peripheral.writeHandle('0017', new Buffer([0x01, 0x00, 0x00]), true, function (error) {
            console.log('BLE: Write handle Error: ' + error);
            peripheral.disconnect();
});
```

The following screenshot shows the characteristic I would like to write 3 Bytes into (Handle 0x0017):

![blehandlewrite](https://f.cloud.github.com/assets/5929579/1906054/72726bc8-7ca8-11e3-8e61-76e3cb5a6389.JPG)

How would the wright parameters look like? Whats the right format for the handle?

And here another somehow related question: 
If I register for a certain notification by writing 0x010000 into the notification characteristic using a handle shortcut, how can I receive the notification events? (I don't want to go through the whole service and characteristics discovery everytime just to set the notify-listener as described in the last part of the "Getting Started Guide" at https://github.com/sandeepmistry/noble/wiki/Getting-started) 

Thanks a lot!
Tom

**Comment by cf-programmers** [comment]
sandeepmistry ,

Thank you very much.
                    peripheral.on('handleNotify', function(handle, value) {} 
works perfectly.
