### ISSUE TITLE
flower-power on Maverick

### ISSUE THREAD

**Issue by markruys** [noble/noble#52]
I'm not sure if this is a Mavericks, a flower-power or a noble issue, but I guess noble... I have troubles reading out a Parrot Flower Power BT 4 device:

```
$ node test.js 
connect
discoverServicesAndCharacteristics
readSystemId
xpcError: connection interrupted
```

I installed the lib via npm install flower-power.

This is a debug trace: http://pastebin.com/VTV8Kyu4

It would be great if I got a clue how to fix this... Thanks.

**Comment by lab101** [comment]
Just had the same error "xpcError: connection interrupted"
Using a Mac Pro with Yosemite 10.10.5.

**Comment by sandeepmistry** [comment]
@markruys please open a new issue, and include a code snippet and debug logs (```DEBUG=* node <file>.js```. Also let me know if you were using a flower power...
