### ISSUE TITLE
RSSI Update Issue

### ISSUE THREAD

**Issue by devans1964** [noble/noble#62]
I am trying to get notified from Noble when RSSI updates.  Simple test code is below

var noble = require('noble');
noble.on('stateChange', function(state) {
  if (state === 'poweredOn' ) {
    //noble.startScanning([],true);
    noble.startScanning([],false);
    console.log('Started Scanning');
  } else {
    noble.stopScanning();
  }
});

noble.on('discover', function(peripheral) {
  console.log('Discovered Peripheral : ' + peripheral.uuid + ' RSSI:' + peripheral.rssi);
  peripheral.connect(function(error){
    if (error == undefined ){
      console.log(peripheral.uuid + ' RSSI:' + peripheral.rssi );
    } else {
      console.log(peripheral.uuid + ' RSSI:' + peripheral.rssi + ' Connecting, Error : ' + error); 
    }
  }); 
  peripheral.updateRssi(function(error, rssi){
    console.log(peripheral.uuid + ' RSSI:' + peripheral.rssi+ ' update RSSI + ' + rssi + ' : Error :' + error);
  });

  peripheral.on('connect',function(){
    console.log(peripheral.uuid +  ' RSSI:' + peripheral.rssi+ ' Has conected');
  }); 
  peripheral.on('rssiUpdate',function(rssi){
    console.log(peripheral.uuid + ' RSSI updated : ' + rssi);

  });
});

I do not get the peripherals connecting nor alerted when RSSI updates
Thanks for your help

Dave

**Comment by loffelmacher** [comment]
i'm seeing similiar strange rssi values when running on Windows compared to what I see when running on Mac. from what i understand Linux and Windows share the same code.

**Comment by sandeepmistry** [comment]
based on the Gitter chatter with @loffelmacher Broadcom based USB adapters the RSSI doesn't seem to go above -59 for whatever reason, but a CSR does.
