### ISSUE TITLE
Connecting to multiple devices using same interface

### ISSUE THREAD

**Issue by arturoribes** [noble/noble#752]
I am experiencing problems connecting to multiple devices on the same interface. If I use the same process to connect to, say, 4 devices, then all connect ok. But if I use 4 processes to connect to 4 devices, then only the first two connect, but the other two processes stay in a "connecting" state.

Is it a limitation that I can only connect to multiple devices using a single process?

**Comment by sandeepmistry** [comment]
It's probably related to the Bluetooth adapter hardware, many adapters have trouble with active connections with they are scanning.
