### ISSUE TITLE
Multiple interfaces problem

### ISSUE THREAD

**Issue by FROeHlyEisvogel** [noble/noble#755]
Hey there,
I habe two bluetooth interfaces on my raspberry pi.
One should be used by noble and the other for continuous scanning.
So the problem is that it seems to be impossible to prevent noble touching the second interface.
It seems like noble is resetting all interfaces when loaded and than also performing commands on the second interface even if the first one is selected.

Greetings
Samuel

**Comment by don** [comment]
Set NOBLE_HCI_DEVICE_ID to control which adapter noble uses

https://github.com/sandeepmistry/noble#multiple-adapters

**Comment by FROeHlyEisvogel** [comment]
Could it be that there is a problem when using this in coffee script?
I did notice now that when I am using the command in a javascript file it does work but not in coffe script.

I am using this command:
process.env['NOBLE_HCI_DEVICE_ID'] = 1

Is there anything I have to change from javascript to coffeescript?

**Comment by don** [comment]
> Is there anything I have to change from javascript to coffeescript?

Probably, especially since it works in JavaScript. I don't use coffeescript so I can't help, sorry.

Another option is to set the env from your shell before calling your script

    sudo NOBLE_HCI_DEVICE_ID=1 node <your file>.js
