### ISSUE TITLE
Bindings being initialized twice or more

### ISSUE THREAD

**Issue by tlongeri** [noble/noble#765]
What title says.

This can be reproduced with the following

```javascript
const noble = require('noble');
noble.on('stateChange', () => {});
noble.on('stateChange', () => {}); 
x = noble.state;
```

I came across this bug when trying out [node-web-bluetooth](https://github.com/IjzerenHein/node-web-bluetooth), and using `btmon` I noticed that ATT MTU Exchange Requests were being sent 4 times when a connection was established. This was because listeners had been attached twice, and the initial MTU Exchange was called on a "chain" of 2 events.

I traced it to the lines 51-72 of `lib/noble.js`:
```javascript
  //lazy init bindings on first new listener, should be on stateChange
  this.on('newListener', function(event) {
    if (event === 'stateChange' && !this.initialized) {
      process.nextTick(function() {
        this._bindings.init();
        this.initialized = true;
      }.bind(this));
    }
  }.bind(this));

  //or lazy init bindings if someone attempts to get state first
  Object.defineProperties(this, {
    state: {
      get: function () {
        if (!this.initialized) {
          this._bindings.init();
          this.initialized = true;
        }
        return this._state;
      }
    }
  });
```

So you can have initialization queued with `process.nextTick`, but `initialized` remains false. Until the initializer actually gets called you can queue any number of other initializations with `.on('stateChange',func)`, which will be later executed. You can also initialize by accessing `noble.state`, which will set `initialized` to true immediately, but will not prevent previously queued initializations from executing.

Edit: I should say this issue is due to changes in version 1.9.0, so I went back to 1.8.1 for now.

**Comment by sandeepmistry** [comment]
Hi @tlongeri,

Could you please try out the changes from PR #769  and provide your feedback. Thanks.

**Comment by AlCalzone** [comment]
I've been getting multiple calls of the "discover" callback since upgrading from 1.8.1 to 1.9.0. #769 fixes it for me. Please merge soon!
