### ISSUE TITLE
Noble/Bleno Mesh Creation and A2DP Programming on Mac OSX

### ISSUE THREAD

**Issue by UsersDoProgram** [noble/noble#768]
I was wondering if Bleno and Noble can create mesh networks alone with the one to many topologies and if they do how could I accomplish this? Any snippets or examples would be appreciated. The other question that I had was how I could program a central node and a peripheral that adhere to the A2DP Profile Specification or if it is even possible with these libraries. Any and all help would be appreciated thank you!

**Comment by sandeepmistry** [comment]
hi @UsersDoProgram,

I have not looked at the mesh spec, so can't comment.

I suggest you post on stackoverflow or the gitter.im channels.

**Comment by UsersDoProgram** [comment]
Thank you for your timely response and will do!
