### ISSUE TITLE
Cannot discover peripherals anymore

### ISSUE THREAD

**Issue by revialim** [noble/noble#776]
I picked up a small project from some time ago, in which I want to scan all bluetooth devices in my area for their uuids, but when I run my script now, it seems to not go into discover mode anymore. I might just miss something trivial... Can somebody tell me, what I'm doing wrong? Any help would be very appreciated.

Here is the script that I'm trying to run. It's basically taken from the test.js file.
```javascript
var noble = require('noble');

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    noble.startScanning([], true); //allow duplicates
  } else {
    noble.stopScanning();
  }
});

noble.on('discover', function(peripheral) {
  var uuid;
  if(peripheral.advertisement.serviceUuids != undefined 
  	  && peripheral.advertisement.serviceUuids != null){
  	uuid = peripheral.advertisement.serviceUuids;
  } else {
  	uuid = "undefined or other";
  }
  console.log('Found device with local name: ' + peripheral.advertisement.localName);
  console.log('advertising the following service uuid\'s: ' + uuid);
  console.log("...");
}
```

**Comment by Matebo** [comment]
Did you find a solution? I'm also not discovering anything.

**Comment by hothsolo** [comment]
It looks to me like you're never turning on the scanner.  Your else statement at the top basically says, "if I'm already on, start scanning and if I'm off, stop scanning."  If you're off, you need to turn it on.  Try this code at the top:


  //if power is already on, start scanning
  if (noble.state === "poweredOn") {
    noble.startScanning([], true);
    console.log("Restarting scan...");
  }
  //if not, toggle the power on
  else {
    noble.on("stateChange", function (state) {
      noble.startScanning([], true);
      console.log("Powered On.  Starting Scan...");
    });
  }

**Comment by Matebo** [comment]
Sorry, i was using @abandonware/noble. With this code the discover event is never called. Installing noble doesn't work because it cannot find module 'bluetooth-hci-socket'. I will look further into the node-ble project.

**Comment by hothsolo** [comment]
Yes, I'm using the abandonware version as well.  The code I posted above works.

**Comment by Matebo** [comment]
What OS are you using? I'm using Debian 11 with kernel version 5.15.5

**Comment by hothsolo** [comment]
Debian 11 on a Raspberry Pi 4.
