### ISSUE TITLE
Docker and Noble

### ISSUE THREAD

**Issue by UsersDoProgram** [noble/noble#788]
Hello, I am trying to build an application that uses an Ubuntu Docker Container with Noble but I have come across a rough patch. When trying to build and run the docker it doesn't go as expected, for one when I run docker build -t x/y, I get the errors shown <a href='https://github.com/UsersDoProgram/BlueScanner/blob/master/log2.txt'>here</a>, it seems that the Noble library isn't properly installed and when running the container another set of issues arise as can be seen <a href='https://github.com/UsersDoProgram/BlueScanner/blob/master/log1.txt'>here</a>.
I'll add the <a href='https://github.com/UsersDoProgram/BlueScanner/blob/master/Dockerfile'>Dockerfile</a> and <a href="https://github.com/UsersDoProgram/BlueScanner/blob/master/main.js">Main.js</a> links so you can pick apart my mistakes. Thanks in advance! I am trying to build this on a Mac running 10.13.

**Comment by sandeepmistry** [comment]
Seems ok, those only appear to be warnings.

**Comment by UsersDoProgram** [comment]
Yes, but when the code is run, it doesn't actually execute or wait on the changes. Execution halts once noble is required.
