### ISSUE TITLE
TypeError: Cannot read property 'services' of undefined

### ISSUE THREAD

**Issue by bmiller59** [noble/noble#85]
Hello. I am running in Mavericks trying to connect my sensortag as a node red module. I have enabled DEBUG=mavericks-bindings and I can see that it discovers and connect correctly and that there is a variety of message activity and then the following. The last debug message I added in the msg70 handler. It appears that the _peripherals object is empty for some reason, leading to the services property to be undefined. Do you know why? Thank you.

 "kCBMsgId": 70
} +1ms
  mavericks-bindings xpcEvent: {
  "kCBMsgArgs": {
    "kCBMsgArgData": [
      216,
      111,
      62,
      129
    ],
    "kCBMsgArgIsNotification": 1,
    "kCBMsgArgCharacteristicHandle": 55,
    "kCBMsgArgDeviceUUID": [
      240,
      167,
      253,
      23,
      136,
      137,
      77,
      233,
      143,
      163,
      91,
      130,
      89,
      49,
      218,
      182
    ]
  },
  "kCBMsgId": 70
} +36s
  mavericks-bindings Msg70 +1ms f0a7fd1788894de98fa35b825931dab6 {} undefined

30 Jul 21:34:32 - [red] Uncaught Exception:
30 Jul 21:34:32 - TypeError: Cannot read property 'services' of undefined
    at nobleBindings.write.sendCBMsg.kCBMsgArgDeviceUUID (/Users/brendan_miller/projects/sensortag/node-red/node_modules/noble/lib/mac/mavericks.js:375:45)
    at emit (events.js:95:17)
    at nobleBindings.sendCBMsg.sendXpcMessage.kCBMsgId (/Users/brendan_miller/projects/sensortag/node-red/node_modules/noble/lib/mac/mavericks.js:41:8)
    at emit (events.js:95:17)
    at null.<anonymous> (/Users/brendan_miller/projects/sensortag/node-red/node_modules/noble/lib/mac/mavericks.js:17:10)
    at XpcConnection.emit (events.js:95:17)

**Comment by vielmetti** [comment]
I'm seeing what I think is this very same error (OS X Mavericks), investigating.

**Comment by FluffyJack** [comment]
Seeing this error on yosemite. Seems like it's loosing the data some time during the connection. It happens only every few messages.

```
/Users/fluffyjack/Developer/mini_drone/node_modules/noble/lib/mac/yosemite.js:525
CBMsgArgCharacteristicHandle: this._peripherals[deviceUuid].services[serviceUu
                                                                    ^
TypeError: Cannot read property '9a66fa000800919111e4012d1540cb8e' of undefined
    at nobleBindings.write (/Users/fluffyjack/Developer/mini_drone/node_modules/noble/lib/mac/yosemite.js:525:74)
    at Noble.write (/Users/fluffyjack/Developer/mini_drone/node_modules/noble/lib/noble.js:270:19)
    at Characteristic.write (/Users/fluffyjack/Developer/mini_drone/node_modules/noble/lib/characteristic.js:64:15)
    at null.<anonymous> (/Users/fluffyjack/Developer/mini_drone/index.js:31:41)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by sandeepmistry** [comment]
@FluffyJack could you please open a new issue for this. The following would be useful:

 * Debug output: ```DEBUG=yosemite-bindings node <file>.js```
 * Access to your code.

The only thing I can think of currently is you are scanning with duplicates and connecting later on. noble's internal peripheral map, would clear it's book keeping then. See: https://github.com/sandeepmistry/noble/blob/master/lib/mac/yosemite.js#L158

**Comment by FluffyJack** [comment]
@sandeepmistry you are totally right. The "fix" is to stop scanning once you've connected, this makes connecting to multiple peripherals next to impossible though because of the race condition caused by the centralised set of commands on noble. Each peripheral, service, and characteristic should be able to manage all of its data on its own, instead of acting as a proxy to the central set of commands to allow this. Would require a large restructuring though. If you're up for it awesome, otherwise if it's something you'd consider a pull request for then I may have a go next time I have time available for it.

**Comment by sandeepmistry** [comment]
@FluffyJack just to confirm, you are scanning with duplicates? What are you connecting to? Is it a Bluetooth 4.1 peripheral that support multiple simultaneous connections?

A potential smaller fix would be, changing:

```javascript
  this._peripherals[deviceUuid] = {
    uuid: uuid,
    advertisement: advertisement,
    rssi: rssi
  };
```

to:

```javascript
 if (!this._peripherals[deviceUuid]) {
  this._peripherals[deviceUuid] = {};
 }
 this._peripherals[deviceUuid].uuid = uuid;
 this._peripherals[deviceUuid].advertisement = advertisement;
 this._peripherals[deviceUuid].rssi = rssi;
```

**Comment by andySigler** [comment]
Just had similar problem on mavericks. The solution was replacing `noble/lib/mac/mavericks.js` line 141 as described by sandeepmistry above.

It seems to me having persistent knowledge of peripherals' services and characteristics is needed when writing applications that call `noble.startScanning()` and `noble.stopScanning()` intermittently. Your commit above fixed this for Yosemite. Maybe include other OSes?

**Comment by sandeepmistry** [comment]
@andySigler would you have time to submit a pull request? Unfortunately, I don't have access to a OS X 10.9 Mac, so it would be great if you could test out the changes and submit a patch.

**Comment by vielmetti** [comment]
I do have a 10.9 Mac (Mavericks) and would be happy to give you as needed
access to it Sandeep if that would help confirm debugging. I'll try this
patch.

On Thu, Apr 16, 2015 at 8:56 PM, Andy Sigler <notifications@github.com>
wrote:

> Just had similar problem on mavericks. The solution was replacing
> noble/lib/mac/mavericks.js line 141 as described by sandeepmistry above.
>
> It seems to me having persistent knowledge of peripherals' services and
> characteristics is needed when writing applications that call
> noble.startScanning() and noble.stopScanning() intermittently. Your
> commit above fixed this for Yosemite. Maybe include other OSes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sandeepmistry/noble/issues/85#issuecomment-93870594>.
>



-- 
Edward Vielmetti +1 734 330 2465
edward.vielmetti@gmail.com

**Comment by andySigler** [comment]
sorry for the delay, just submitted my tested changes. Peripherals on mavericks are not overwritten when repeatedly recognized between calls to `.startScanning()`
