### ISSUE TITLE
Can't discover peripheral on OSX

### ISSUE THREAD

**Issue by ervinewell** [noble/noble#895]
I create a BLE peripheral with lightBlue app, and I can discover this on another android phone, but cannot discover this with noble as following:

```javascript
const noble = require('noble')

noble.on('discover', function(peripheral) {
  console.log(peripheral) // cannot get anything here
});

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    noble.startScanning([], true);
  } else {
    noble.stopScanning();
  }
});
```

OSX: 10.14
node: 10.16.0

**Comment by jaewonha** [comment]
same here

**Comment by jaewonha** [comment]
I used https://github.com/Timeular/noble-mac as an alternative and its working

**Comment by ervinewell** [comment]
> I used https://github.com/Timeular/noble-mac as an alternative and its working

It works. Thanks a lot.
