### ISSUE TITLE
noble warning: unknown handle 64 disconnected!

### ISSUE THREAD

**Issue by souimanga** [noble/noble#898]
Hi 
thanks for your work !

On a Rp3, I’m using « homebridge » with the plugin « homebridge-mi-flower-care » 
After several days, I have this error :

noble warning: unknown handle 64 disconnected!

Could you help me to find the problem ?
What files do you need ?

Thanks

**Comment by jpalo** [comment]
Any idea what is/was causing this? Seeing same error but on my custom nodeJS app.

**Comment by Stan92** [comment]
Have also the same error noble warning: unknown handle 72 disconnected! (windows 10)
