### ISSUE TITLE
How noble is compatible with the new macOS(10.15 Catalina)

### ISSUE THREAD

**Issue by Barryyang1119** [noble/noble#899]
How noble is compatible with the new macOS(10.15 Catalina)?
Error: Could not start scanning, state is unknown (not poweredOn) at Noble.scan
Thank you so much!

**Comment by Barryyang1119** [comment]
if (osRelease < 13  ) {
  module.exports = require('./legacy');
} else if (osRelease < 14) {
  module.exports = require('./mavericks');
} else if (osRelease < 17) {
  module.exports = require('./yosemite');
} else {
  module.exports = require('./highsierra');
}

**Comment by jakehawkes** [comment]
FYI: https://github.com/abandonware/noble/issues/36

**Comment by ScreamZ** [comment]
So what's to do ? :(
