### ISSUE TITLE
Does not install correctly - Cannot find module 'xpc-connection' or 'bluetooth-hci-socket'

### ISSUE THREAD

**Issue by mrkking** [noble/noble#918]
### Steps to reproduce
npm install noble
create index.js file with contents:
    `const Noble = require('noble'); `
    `Noble.startScanning([], true);`

node index.js

 Xcode already installed
 OS: MAC Catalina
 Node: tried version 13.2.0, 13.1.0, 10.11.0, 9.xx.xx (last in version)
 tried to install xpc-connection - no luck

Also
 Raspberry Pi 3:
 tried same node versions as above
 tried to install bluetooth-hci-socket - no luck

### Error:
`Error: Cannot find module 'xpc-connection' - on MAC`
`Error: Cannot find module 'bluetooth-hci-socket'` - on RPI3

none of these libraries build properly xpc-connection or bluetooth-hci-socket for this project

**Comment by ierome** [comment]
Refer to theGecko forked version of noble. Worked for me.

**Comment by jakehawkes** [comment]
FYI: https://github.com/abandonware/noble/issues/36

**Comment by jakehawkes** [comment]
> theGecko

And how would one find that?

**Comment by rzr** [comment]
Any patch from @theGecko to be picked ?

**Comment by thegecko** [comment]
The best version of noble today seems to be:

https://github.com/abandonware/noble

My [outstanding patch](https://github.com/abandonware/noble/pull/31) there just adds types.
