### ISSUE TITLE
Buffer automatically converting hexadecimal to decimal

### ISSUE THREAD

**Issue by sujitpatil72** [noble/noble#925]
I am using noble Bluetooth library and it accepts only buffer type while writing to write characteristics, whenever I tried to create buffer using hexadecimal but it's automatically getting converted to decimal values and hence my Bluetooth device is not understanding the packet sent.

const buf = Buffer.allocUnsafe(4);

    buf.writeUInt8(0x3, 0);
    buf.writeUInt8(0x4, 1);
    buf.writeUInt8(0x5c, 2);
    buf.writeUInt8(0x42, 3);

    console.log(buf);
    //Expected Output: <Buffer 03 04 5c 42>
    //Current Output: Buffer(4) [3, 4, 92, 66]
Converting hexadecimal to string is not an option as my Bluetooth device expects only hexadecimal values

**Comment by buildog** [comment]
@sujitpatil72 could you please explain how you solved this issue ?
