### ISSUE TITLE
How noble is compatible with the new macOS(10.15 Catalina)?

### ISSUE THREAD

**Issue by lwj06** [noble/noble#930]

**Comment by rzr** [comment]
Please try this version:
https://www.npmjs.com/package/@abandonware/noble/v/1.9.2-8

And report issues also to:
https://github.com/abandonware/noble/issues

**Comment by lwj06** [comment]
> Please try this version:
> https://www.npmjs.com/package/@abandonware/noble/v/1.9.2-8
> 
> And report issues also to:
> https://github.com/abandonware/noble/issues

I didn't use this version before. Every time when the Mac OS system upgrade, I just need to change the kCBMsgId corresponding to the API in noble to be compatible with the new version of the system. In this 10.15.4, I found that the kCBMsgId was also changed, but the main problem is that the discoverservices callback didn't bring the servicesuuid parameter
