### ISSUE TITLE
Alpine Linux - Dependencies

### ISSUE THREAD

**Issue by carlosanunes** [noble/noble#954]
The README does not specify the required dependencies for Noble in Alpine Linux. I am guessing the bluez and bluez-libs are part of them but seeking confirmation on full required list.

**Comment by rzr** [comment]
It looks the maintenance of this project is in pause, but feel free to contribute to @abandonware fork until upstream is active again

Feel free to comment:
https://github.com/abandonware/noble/issues/2

**Comment by carlosanunes** [comment]
Just so as to leave here what was my solution.

The libraries that resolved the dependencies: bluez, libudev-zero and libudev-zero-dev.
