### ISSUE TITLE
Multipe Adapter custom binding

### ISSUE THREAD

**Issue by gharshaw** [noble/noble#981]
Would someone be able to give me an example of the correct option settings that should be coded into the "my-custom-bindings" script in order to specifiy a particular bluetooth adapter?
var noble = require('noble/with-bindings')(require('./my-custom-bindings'));

Thank you

**Comment by rzr** [comment]
Please check if problem is also present with downstream community maintained fork:

https://github.com/abandonware/noble

If yes please report issue there too
